### ISSUE TITLE
run on ARM?

### ISSUE THREAD

**Issue by erdkinder** [conrad784/docker-mediathekview-webinterface#10]
Hello,

just tried to install on my Odroid HC4, running my OpenMediaVault. But I get this message:

`WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
`

I'm still new to docker. Is it possible to get somehow installed on an ARM?

best regards
Felix

**Comment by conrad784** [comment]
Sorry I mislead you, the base image I am using does not support any ARM versions (yet?) https://github.com/jlesage/docker-baseimage-gui/issues/35
As I am not interested in also supporting the  base image and I am currently have no use case for it, I will not invest any time in adding those, sorry.

**Comment by conrad784** [comment]
The base image was extended for ARM versions, I am building and pushing them now, but I have not tested the containers to be working like intended.
