### ISSUE TITLE
Can MV be updated manually?

### ISSUE THREAD

**Issue by Goeste** [conrad784/docker-mediathekview-webinterface#6]
Hi,

quick question, can the tool MV be updated manuall somehow? Or has the whole containter to be updated by you?

Best,
goeste

**Comment by conrad784** [comment]
It would be possible to add download + unzip to the startup script to always fetch the latest version. But this is contradictory to why I want to use containers. I want to have a single version and roll back at will to an older version, therefore I am creating fixed version containers.

**Comment by Goeste** [comment]
ok strange... on github you state it is the latest version, on dockerhub however it pulls version 13.5.1...
