### ISSUE TITLE
Can settings and Abos be made persistant?

### ISSUE THREAD

**Issue by Goeste** [conrad784/docker-mediathekview-webinterface#7]
Hi,
can the settings and Abos one sets up be made persistant for a container restart or later container update?

Best, goeste

**Comment by conrad784** [comment]
I you persist the data on your disk `-v $HOME/.mediathek3:/config:rw` or in a [volume](https://docs.docker.com/storage/volumes/) they will survive a container restart. Containers should never rely on persistent storage in themselves.

**Comment by Goeste** [comment]
ok, had that in place... however it somehow got resettet... maybe check my settings again... THANKS!
