### ISSUE TITLE
Supress update warnings

### ISSUE THREAD

**Issue by martinjuhasz** [conrad784/docker-mediathekview-webinterface#9]
So there is a new version available for mediathekview.
Is there some way to supress the update notification on bootup of the dockerfile?

It will stay in this screen until it gets clicked away. meaning that a docker restart of that container will halt the mediathekview until i went there and click it away. No "abos" will run until this is gone.

![Screenshot 2021-08-26 at 13 32 16](https://user-images.githubusercontent.com/204190/130955668-d39dcb2c-0ab8-498d-b96e-2d64ed14d76a.png)

**Comment by Goeste** [comment]
an update to the docker would be great!

**Comment by conrad784** [comment]
@martinjuhasz from what I am reading in the forum, you can block the update notification via settings.xml https://forum.mediathekview.de/topic/4393/meldung-software-update-abschalten-version-13-7-1/5?_=1632290941746

I don't want to add some sed commands to the startup script and make this decision for the user, because in the worst case this might corrupt the settings.xml file?

**Comment by conrad784** [comment]
@Goeste  I am still on 13.6 as this is the latest version which could be run as cli, therefore my motivation to stay up-to-date is not that high... Thanks for reminding me :D

**Comment by martinjuhasz** [comment]
> @martinjuhasz from what I am reading in the forum, you can block the update notification via settings.xml https://forum.mediathekview.de/topic/4393/meldung-software-update-abschalten-version-13-7-1/5?_=1632290941746
> 
> I don't want to add some sed commands to the startup script and make this decision for the user, because in the worst case this might corrupt the settings.xml file?

This would be perfectly fine for running this in a docker environment. Sadly the `automatic_update_check` setting did **not** work for me.

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<settings>
  <application>
    <user_agent>MediathekView</user_agent>
    <ui>
      <install_tab_listeners>true</install_tab_listeners>
      <tray>
        <use>false</use>
      </tray>
      <mainwindow>
        <maximized>true</maximized>
        <width>1282</width>
        <height>774</height>
        <location>
          <x>-1</x>
          <y>-1</y>
        </location>
      </mainwindow>
      <filter_dialog>
        <width>412</width>
        <height>632</height>
        <location>
          <x>57</x>
          <y>83</y>
        </location>
        <visible>false</visible>
      </filter_dialog>
    </ui>
    <buttons_panel>
      <visible>false</visible>
    </buttons_panel>
    <automatic_update_check>false</automatic_update_check>
    <notifications>
      <native_support>false</native_support>
      <show_native>false</show_native>
    </notifications>
  </application>
  … 
</settings>

```

I'm still seeing this udate screen when starting the docker

**Comment by lukengda** [comment]
In case someone else might stumble upon this issue as well, i want to leave this info:

The xml flag in the settings does prevent the popup from opening that opens after MediathekView has started. But MediathekView has two separate update checkers. And the one coming from install4j, i was not able to get this removed.
